"""signin for org

Revision ID: 27eb5faa663f
Revises: 2d3f2f53c2b9
Create Date: 2024-10-24 08:02:21.201370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27eb5faa663f'
down_revision: Union[str, None] = '2d3f2f53c2b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint(None, 'organizations', ['organization_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'organizations', type_='unique')
    # ### end Alembic commands ###
