"""update oraganizatio

Revision ID: 2d3f2f53c2b9
Revises: d924ef1a8d16
Create Date: 2024-10-24 06:46:04.212542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2d3f2f53c2b9'
down_revision: Union[str, None] = 'd924ef1a8d16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index(op.f('ix_organizations_organization_name'), 'organizations', ['organization_name'], unique=True)
    # op.create_unique_constraint(None, 'organizations', ['organization_email'])
    op.drop_column('organizations', 'address')
    op.drop_column('organizations', 'name')
    op.drop_column('organizations', 'contact_person')
    op.drop_column('organizations', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('email', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('organizations', sa.Column('contact_person', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('organizations', sa.Column('name', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('organizations', sa.Column('address', mysql.TEXT(), nullable=True))
    # op.drop_constraint(None, 'organizations', type_='unique')
    # op.drop_index(op.f('ix_organizations_organization_name'), table_name='organizations')
    # ### end Alembic commands ###
