"""Tenants signin and signup code added and relationship with org 

Revision ID: 48c572dbe268
Revises: 5a993990a8f4
Create Date: 2024-10-24 13:15:33.433004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48c572dbe268'
down_revision: Union[str, None] = '5a993990a8f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
