"""Tenants signin and signup code added

Revision ID: 5a993990a8f4
Revises: cdb81f2670b3
Create Date: 2024-10-24 11:59:52.928272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5a993990a8f4'
down_revision: Union[str, None] = 'cdb81f2670b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('password', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'tenants', 'organizations', ['org_id'], ['org_id'])
    op.drop_column('tenants', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.drop_column('tenants', 'password')
    # ### end Alembic commands ###
