"""new field added in org

Revision ID: d924ef1a8d16
Revises: d7b51da65538
Create Date: 2024-10-24 06:30:34.364960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd924ef1a8d16'
down_revision: Union[str, None] = 'd7b51da65538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('organizations', sa.Column('organization_name', sa.String(length=255), nullable=False))
    # op.add_column('organizations', sa.Column('first_name', sa.String(length=255), nullable=False))
    # op.add_column('organizations', sa.Column('last_name', sa.String(length=255), nullable=True))
    # op.add_column('organizations', sa.Column('organization_address', sa.Text(), nullable=True))
    # op.add_column('organizations', sa.Column('organization_email', sa.String(length=255), nullable=False))
    # op.add_column('organizations', sa.Column('password', sa.String(length=255), nullable=False))
    # op.add_column('organizations', sa.Column('role', sa.String(length=100), nullable=False))
    # op.drop_index('email', table_name='organizations')
    # # op.drop_index('ix_organizations_name', table_name='organizations')
    # op.create_index(op.f('ix_organizations_organization_name'), 'organizations', ['organization_name'], unique=True)
    # op.create_unique_constraint(None, 'organizations', ['organization_email'])
    # op.drop_column('organizations', 'email')
    # op.drop_column('organizations', 'name')
    # op.drop_column('organizations', 'address')
    # op.drop_column('organizations', 'contact_person')
    # # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('organizations', sa.Column('contact_person', mysql.VARCHAR(length=255), nullable=True))
    # op.add_column('organizations', sa.Column('address', mysql.TEXT(), nullable=True))
    # op.add_column('organizations', sa.Column('name', mysql.VARCHAR(length=255), nullable=True))
    # op.add_column('organizations', sa.Column('email', mysql.VARCHAR(length=255), nullable=True))
    # op.drop_constraint(None, 'organizations', type_='unique')
    # op.drop_index(op.f('ix_organizations_organization_name'), table_name='organizations')
    # op.create_index('ix_organizations_name', 'organizations', ['name'], unique=True)
    # op.create_index('email', 'organizations', ['email'], unique=True)
    # op.drop_column('organizations', 'role')
    # op.drop_column('organizations', 'password')
    # op.drop_column('organizations', 'organization_email')
    # op.drop_column('organizations', 'organization_address')
    # op.drop_column('organizations', 'last_name')
    # op.drop_column('organizations', 'first_name')
    # op.drop_column('organizations', 'organization_name')
    # # ### end Alembic commands ###
