"""update user and create oragnization table

Revision ID: dd378c2439eb
Revises: 345ffcd28e25
Create Date: 2024-10-23 12:08:20.154808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dd378c2439eb'
down_revision: Union[str, None] = '345ffcd28e25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('org_id', sa.Integer(), nullable=True))
    # op.add_column('users', sa.Column('username', sa.String(length=255), nullable=True))
    # op.add_column('users', sa.Column('first_name', sa.String(length=255), nullable=True))
    # op.add_column('users', sa.Column('last_name', sa.String(length=255), nullable=True))
    # op.add_column('users', sa.Column('role', sa.String(length=50), nullable=True))
    # op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # op.alter_column('users', 'password_hash',
    #            existing_type=mysql.VARCHAR(length=260),
    #            type_=sa.String(length=255),
    #            existing_nullable=True)
    # op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # op.create_foreign_key(None, 'users', 'organizations', ['org_id'], ['org_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'users', type_='foreignkey')
    # op.drop_index(op.f('ix_users_username'), table_name='users')
    # op.alter_column('users', 'password_hash',
    #            existing_type=sa.String(length=255),
    #            type_=mysql.VARCHAR(length=260),
    #            existing_nullable=True)
    # op.drop_column('users', 'is_active')
    # op.drop_column('users', 'created_at')
    # op.drop_column('users', 'role')
    # op.drop_column('users', 'last_name')
    # op.drop_column('users', 'first_name')
    # op.drop_column('users', 'username')
    # op.drop_column('users', 'org_id')
    # # ### end Alembic commands ###
